name: red_point
description: Red River Gorge Climbing Guide
homepage: https://rchowell.github.io

publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.6
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  photo_view: ^0.13.0
  shared_preferences: ^2.0.8
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/db.sqlite3
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_1024.png"

