name: red_point
description: Red River Gorge Climbing Guide
version: 0.2.0+3
author: R. C. Howell
homepage: http://rchowell.github.io

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1+1
  path_provider: ^1.6.14
  charts_flutter: ^0.9.0
  url_launcher: ^5.5.3
  cached_network_image: ^2.3.2+1
  flutter_cache_manager: ^1.4.2
  photo_view: ^0.10.2
  shared_preferences: ^0.5.10
  flutter_map: ^0.10.1+1
  geolocator: #^3.0.0
    git:
      url: git://github.com/yannickvg/flutter-geolocator
      ref: feat/update_google_api_availability_for_androidx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  assets:
    - assets/db.sqlite3

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_1024.png"
